// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

public type User record {
    # the username of the user
    string username?;
    # the first name of the user
    string firstname?;
    # the last name of the user
    string lastname?;
    # the email address of the user
    string email?;
};

public type inline_response_201 record {
    # the username of the user newly created
    string userid?;
};
